"""add_rooms_tenants_invoices_payments

Revision ID: 7edc5e2e780a
Revises: 8ac67e0e9d38
Create Date: 2026-02-27 08:58:33.492943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7edc5e2e780a'
down_revision: Union[str, Sequence[str], None] = '8ac67e0e9d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('id_card', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('check_in_date', sa.DateTime(), nullable=True),
    sa.Column('check_out_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'late', name='invoicestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Clear existing payments data before schema changes
    op.execute('DELETE FROM payments')
    # Drop foreign key constraint first before dropping bookings table
    op.drop_constraint(op.f('payments_booking_id_fkey'), 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_column('payments', 'booking_id')
    op.drop_table('bookings')
    op.add_column('payments', sa.Column('invoice_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payments', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.add_column('rooms', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('rooms', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'is_available')
    op.add_column('payments', sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_booking_id_fkey'), 'payments', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_column('payments', 'invoice_id')
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'terminated', name='bookingstatus'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('bookings_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.drop_table('invoices')
    op.drop_table('tenants')
    # ### end Alembic commands ###
